### ISSUE TITLE
Cannot find module 'beam-client-node/lib/ws'

### ISSUE THREAD

**Issue by trunght-afkvr** [mixer/beam-client-node#70]
I am trying to update to 1.x.x from 0.13.0, when I try to run there is this error "cannot find module 'beam-client-node/lib/ws'

I believe I had ws 1.0.0 installed with 0.13.0 (since 0.13.0 required ws 1.0.0)

**Comment by SimonSchick** [comment]
The project structure was changed with v1 (hence the breaking change), you should be able to import all contents from the root package eg. `beam-client-node`.

**Comment by trunght-afkvr** [comment]
@SimonSchick  thank you for the reply.
I am a newbie in node, I am sorry if my question is stupid here, what do you mean by import all contents from root package.

Currently I just change the version of beam-client-node in package.json to 1.0.0 and run 'npm install'

**Comment by trunght-afkvr** [comment]
Sorry, my mistake, in my code I required beam-client-node/lib/ws.
